export const LITE_LISTONE_REQUEST = "LITE_LISTONE_REQUEST"
export const LITE_LISTONE_SUCCESS = "LITE_LISTONE_SUCCESS"
export const LITE_LISTONE_FAIL = "LITE_LISTONE_FAIL"

export const LITE_LIST_REQUEST = "LITE_LIST_REQUEST"
export const LITE_LIST_SUCCESS = "LITE_LIST_SUCCESS"
export const LITE_LIST_FAIL = "LITE_LIST_FAIL"