export const ORDER_LISTONE_REQUEST = "ORDER_LISTONE_REQUEST"
export const ORDER_LISTONE_SUCCESS = "ORDER_LISTONE_SUCCESS"
export const ORDER_LISTONE_FAIL = "ORDER_LISTONE_FAIL"

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST"
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS"
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL"