export const TALENT_FIND_REQUEST = "TALENT_FIND_REQUEST"
export const TALENT_FIND_SUCCESS = "TALENT_FIND_SUCCESS"
export const TALENT_FIND_FAIL = "TALENT_FIND_FAIL"

export const TALENT_FINDONE_REQUEST = "TALENT_FINDONE_REQUEST"
export const TALENT_FINDONE_SUCCESS = "TALENT_FINDONE_SUCCESS"
export const TALENT_FINDONE_FAIL = "TALENT_FINDONE_FAIL"

export const TALENT_SEARCH_REQUEST = "TALENT_SEARCH_REQUEST";
export const TALENT_SEARCH_SUCCESS = "TALENT_SEARCH_SUCCESS";
export const TALENT_SEARCH_FAIL = "TALENT_SEARCH_FAIL"

export const TALENT_PAGING_REQUEST = "TALENT_PAGING_REQUEST"
export const TALENT_PAGING_SUCCESS = "TALENT_PAGING_SUCCESS"
export const TALENT_PAGING_FAIL = "TALENT_PAGING_FAIL"
